### ISSUE TITLE
Error: keepalive ping timeout; no close frame received

### ISSUE THREAD

**Issue by roerohan** [deepgram/deepgram-python-sdk#326]
## What is the current behavior?

I get the following error intermittently while sending audio packets over the deepgram socket connection.

```
sent 1011 (internal error) keepalive ping timeout; no close frame received
```

This is often followed by the log
```
[SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2706)
```

## Steps to reproduce

```py
# Code to check if the socket connection is live
while len(self._speech_buffer):
	await self.deepgram_live._socket.send(self._speech_buffer.pop(0))
   	logger.debug("Sent speech from {}", self.peer_id)
```

P.S. the reason why I'm using the `_socket` object is that I'm using `deepgram-sdk==2.11.0` and I had reported an [issue](https://github.com/deepgram/deepgram-python-sdk/issues/183#issuecomment-1837519417) in the past with this version. As you mentioned, the issue was fixed in a new major version, but we haven't gotten around to updating it since it had been working fine for us all this while.

## Expected behavior

The socket connection should not close abruptly.

## Please tell us about your environment

Operating System/Version: Linux 5.10.209-198.812.amzn2.x86_64 (AWS Ubuntu)
Python Version: 3.10.12

## Other information

This error only occurs once in a while, and most often when there are multiple parallel socket connections to deepgram live.

**Comment by dvonthenen** [comment]
For this issue, the socket isn't receiving any data nor the keepalive message. That is expected behavior, but the SSL error is of concern. I don't have enough experience with the older version, so I will need to take some time to look at it. 

PS: I re-opened this issue https://github.com/deepgram/deepgram-python-sdk/issues/326 in order to take a look at it, but not sure when I am going to get time as I have a bunch of things on my plate.

**Comment by dvonthenen** [comment]
@sandra said should would take a look at this issue and the other one since she has more knowledge about the `v2` client.

**Comment by ToxicityMax** [comment]
We recently migrated to v3 and implemented the flag `options={"keepalive": "true"}` in `DeepgramClientOptions` to maintain websocket connections. However, we're encountering the same persistent issue where, intermittently, the following error floods the logs, leading to a disruption in receiving transcripts:

This error seems to occur occasionally, but once it starts, it prevents us from receiving any further transcripts through that connection. Despite setting the keepalive flag, this issue persists.

It would be helpful if there are specific troubleshooting steps or additional configurations we should consider to mitigate this issue

**Comment by dvonthenen** [comment]
> We recently migrated to v3 and implemented the flag `options={"keepalive": "true"}` in `DeepgramClientOptions` to maintain websocket connections. However, we're encountering the same persistent issue where, intermittently, the following error floods the logs, leading to a disruption in receiving transcripts:

Hi @ToxicityMax This reported issue is for `v2` of the SDK. If you are having problems with `v3`, reach out to discuss in Discord or create a new issue. Before you do, please update to the latest `v3.1.7` of the SDK.

**Comment by rutvik106** [comment]
@ToxicityMax any success with this. I too get "WebSocketException: received 1011 (internal error) Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001; then sent 1011 (internal error) Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001" even if keep alive is passed as true.

**Comment by dvonthenen** [comment]
Hi @rutvik106 

If this is for `v3` and you are having problems, please create another issue since this issue is specifically for `v2`.

Since we get this question a lot, here are some examples to demonstrate expected failures when not using and also how to utilize the feature: correctlyhttps://github.com/deepgram/deepgram-python-sdk/pull/348

**Comment by prismvineeth** [comment]
Still getting this issue when using websocket with deepgram-sdk==3.7.3 using both listen and speak options.

**Comment by prismvineeth** [comment]
Is [this](https://developers.deepgram.com/reference/transform-text-to-speech-websocket#ping-pong-messages) taken care of in Python SDK ?

**Comment by dvonthenen** [comment]
> Is [this](https://developers.deepgram.com/reference/transform-text-to-speech-websocket#ping-pong-messages) taken care of in Python SDK ?

Ping/pong messages are handled using the lower level websocket library (and is present automatically).

**Comment by dvonthenen** [comment]
> Still getting this issue when using websocket with deepgram-sdk==3.7.3 using both listen and speak options. Especially since the upgrade to 3.7.3.

This is typically due to a mismatch between the actually audio stream encoding and the `encoding` and/or `sample_rate` values set in the options. This is definitely working correctly and I would invite you to run the example in the repo:
https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/speech-to-text/websocket/http/main.py

**Comment by prismvineeth** [comment]
I see... The issue seems to be at 10s into connection without any input, which kind of aligns with the websocket timeout correct ?

**Comment by dvonthenen** [comment]
When you get a disconnect at roughly between 10 and 12 seconds, that's usually an indication that the deepgram endpoint isn't receiving any audio bytes at all. The server will force the disconnect at about that time.

**Comment by dvonthenen** [comment]
Your options are:
1. always send audio (this counts against transcription time = $$)
2. send the keepalive message before the timeout (ie every 10 seconds)
3. [enable the functionality](https://developers.deepgram.com/docs/using-client-options-with-sdks#python-client-options-interface) to do this for you in the SDK: [Example](https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/speech-to-text/websocket/microphone/main.py#L28-L31)

**Comment by prismvineeth** [comment]
> Your options are:
> 
> 1. always send audio (this counts against transcription time = $$)
> 2. you send the keepalive message before each timeout (ie every 10 seconds)
> 3. [enable the functionality](https://developers.deepgram.com/docs/using-client-options-with-sdks#python-client-options-interface) to do this for you in the SDK: [Example](https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/speech-to-text/websocket/microphone/main.py#L28-L31)

Ah that is why I am confused. I am already using
`config = DeepgramClientOptions(options={"keepalive": "true"})`
and
`self._dg_connection = self._deepgram.listen.websocket.v("1")`

And [https://developers.deepgram.com/reference/transform-text-to-speech-websocket#keeping-connections-open](url) - it says we should not send keepalive for websocket. But you mentioned otherwise.

**Comment by dvonthenen** [comment]
I think we are hijacking this thread. If you want to discuss further, I invite you to chat on Discord for more details.

To answer this last question, KeepAlive doesn't apply to TTS which are the docs you are citing.

**Comment by dvonthenen** [comment]
Will not fix. Please migrate to `v3`.
