### ISSUE TITLE
Pyright type definitions check fails with upgrade to 3.1.5

### ISSUE THREAD

**Issue by noxan** [deepgram/deepgram-python-sdk#327]
## What is the current behavior?
- Upgraded from 3.1.4 to 3.1.5 and pyright fails
- `Cannot access member "v" for type "LiveClient". Member "v" is unknown. Pylance[reportAttributeAccessIssue]`

## Steps to reproduce
- Upgraded from 3.1.4 to 3.1.5 and pyright fails
- Use regular example (same for async client by the way)

## Expected behavior
- It should not report any issues like it did before

**Comment by dvonthenen** [comment]
Apparently, `pyright` doesnt like the Union of multiple return types because the classes are dynamically returned. This was done in an effort to fix this issue: https://github.com/deepgram/deepgram-python-sdk/issues/311. Will selectively revert some changes, but someone is going to be unhapp. Will need to investigate how to handle this.

**Comment by dvonthenen** [comment]
Fixed in this release:
https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.1.6

**Comment by noxan** [comment]
thanks @dvonthenen :)
