### ISSUE TITLE
Clarify Support for Examples on Windows

### ISSUE THREAD

**Issue by ThatOneBrownKid** [deepgram/deepgram-python-sdk#340]
## What is the current behavior?
Could not open socket: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000) is the error I get when trying to run the Streaming Microphone example.

## Steps to reproduce

Trying to run the Steaming Microphone example. 

## Expected behavior

Not sure yet, I want to see what the code does, but I can't get past this issue. 

## Please tell us about your environment

- **Operating System/Version:** Windows 10
- **Python Version:** 3.12.2

## Other information

Could not open socket: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)

**Comment by dvonthenen** [comment]
The streaming microphone example will likely not work for Windows. I need to look into creating examples suitable for MS platforms.

**Comment by ThatOneBrownKid** [comment]
> The streaming microphone example will likely not work for Windows. I need to look into creating examples suitable for MS platforms.
> 
> In the meantime, I will update the documentation to reflect this.

Would u recommend using something WSL in order to  use Ubuntu on windows?

**Comment by dvonthenen** [comment]
portaudio supposedly works on Windows, but I have tried it. I suspect there probably are going to be some "gotchas" with using... like additional steps or etc. I just haven't used windows in a while and would need to investigate it.

Likewise, I am not sure WSL will work on portaudio because it would require WSL to expose all devices from the laptop/computer/etc to the WSL environment. I am not sure that if that happens or not. The only way would be to try, but I suspect it probably doesn't.

**Comment by dvonthenen** [comment]
This is available in the latest release:
https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.3.0
