### ISSUE TITLE
SpeechStarted gets triggered by background noise

### ISSUE THREAD

**Issue by AurumnPegasus** [deepgram/deepgram-python-sdk#403]
## What is the current behavior?

When using vad_events flag in deepgram api call, SpeechStarted flag is often set to true due to background noise (especially when the transcription has just started, but sometimes in between as well). This does not reliably allow transcription of speech to text due to it being set off unpredictably. 

## Expected behavior

Expected behaviour is to have better sensitivity of SpeechStarted flag towards background noise, or you could add a feature to tune the sensitivity of vad events flag to manually set based on sensitivity required.

## Please tell us about your environment

Python Version: 3.10.12
OS: Ubuntu 22.04, also tried on MacOS
Making requests to: api.deepgram.com/v1/listen

**Comment by dvonthenen** [comment]
This has been a known problem since before the release of the feature and engineering is aware of this. Even the name of the event is misleading, but that is the name chosen via the API Spec. The event really should be called Noise Detection. 

My recommendation would be to use a client-side VAD anyway since using this feature for that reason is probably not going to be favorable for your use case since this is server side. You incur a network round trip time just to tell you if someone has started to speak in the microphone which just doesn't make too much sense. Despite these recommendations, if you still want to implement server side... enable IntermResults to true and wait for the first word detected essentially gives you a similar result.

Closing this issue since this isn't an issue with the SDK, but rather the implementation of the API.

**Comment by islingtonrobotica** [comment]
Hey, @dvonthenen do you know if there are any plans to change this in the future? The documentation makes it seem like it's a very advanced VAD feature, when it's simply a noise detector. This is from the documentation:

"By gauging tonal nuances in human speech, the VAD can effectively differentiate between silent and non-silent audio segments, providing immediate notification of speech detection."

I feel like this is nowhere near the actual experience and it's a little frustrating. I can snap my fingers and SpeechStarted gets triggered.

**Comment by dvonthenen** [comment]
hi @islingtonrobotica 

I don't believe there are plans to change this at the moment, and personally, I agree entirely with your assessment. Even if it did work, I think the ideal solution would be to use a client-side VAD anyway. You don't want to introduce latency and using a server event (which incurs a roundtrip network notification) to determine if "start of speech" happens client-side, is far from ideal.

**Comment by chisanen** [comment]
Hey @davidvonthenen is there a way to implement client-side VAD for react native expo? Do you know of any methods or resources?
