### ISSUE TITLE
Dictation feature does not work when punctuation characters are spoken after a pause

### ISSUE THREAD

**Issue by rpriyanshu9** [deepgram/deepgram-python-sdk#441]
## What is the current behavior?

When the punctuation characters are spoken after the brief pause, deepgram doesn't return any results back. Eg.:
If I state...
"The patient presents today complaining of a headache {period}"

The service correctly returns...
"The patient presents today complaining of a headache."

However if I say...
"The patient presents today complaining of a headache"

Wait for that text to return and then say...
"Period"

I receive a result from the service, but the text is empty, the confidence is 0. This is the behaviour for all the punctuation characters like comma, colon, question mark, etc.

## Steps to reproduce

Enable `punctuate` and `dictation` settings in the SDK and try to generate the above provided example speech. 

## Expected behavior

Even after the pause, deepgram should recognise punctuation characters.

## Please tell us about your environment

- **Operating System/Version:** MacOS 14.5
- **Python Version:** v3.12.3

## Other information

Related discord thread:
- https://discord.com/channels/1108042150941294664/1196483449024942100/1196483449024942100

**Comment by dvonthenen** [comment]
Hi @rpriyanshu9 

I believe if you have `punctuate` and `dictation` enabled, that is the expected behavior. If you want to verbally provide the punctuation, then you need to set `punctuate` to false (or omit declaring it which is equal to false). If that doesn't give you what you are anticipating, I can forward this to the engineering team with the feedback.

Depending on your use case, you might want to try using the `conversationalai` [model](https://developers.deepgram.com/docs/model).

If you are doing medical-related work (as your examples might suggest), we have a medical model. However, I believe it requires moving into a growth plan (meaning you need to talk to a sales rep).

**Comment by dvonthenen** [comment]
If you want to discuss further or to flush out a proposal for a desired behavior that I can take to engineering, I would be happy to discuss in Discord. Here is the link to join:
https://dpgr.am/discord

Drop me a DM.
