### ISSUE TITLE
Cannot import Deepgram

### ISSUE THREAD

**Issue by fireflyseo** [deepgram/deepgram-python-sdk#83]
Hi, I've installed deepgram via "pip install deepgram-sdk"

The installation is successful, and the deepgram-sdk appears in my Python Lib/site-packages/ folder with the __init__.py file inside.

After the successful install, I attempt to import to my script with "from deepgram import Deepgram"

But Eclipse keeps showing "Unresolved import: Deepgram"

Not sure exactly why this is happening, as this is the first time something like this has happened to me. Any help would be greeatly appreciated.

**Comment by jjmaldonis** [comment]
Hey @fireflyseo, this issue is fairly old now so I'm going to close it. If you are still having issues feel free to reopen.

My guess is that Eclipse does not know where your `Lib/site-packages/` folder is on your computer. You may need to change Python environments in Eclipse or update Eclipse's `PYTHONPATH` environment variable.
